### ISSUE TITLE
Requesting Player rotator feature

### ISSUE THREAD

**Issue by Psychotech1164** [Dean2k/ReModCE#1]
There is already a ReMod compatible version of Player Rotator, but not compatible with ReModCE Ares. Would be great if you added that feature so that we would be able to do avatar/player rotation.

**Comment by JackMidnightVR** [comment]
yes that would be cool allowing to spin yourself not just head like entire avatar in halfbody/fullbody/desktop

**Comment by Dean2k** [comment]
Added
