### ISSUE TITLE
Cannot disable custom theme/image

### ISSUE THREAD

**Issue by UltraHQ** [Dean2k/ReModCE#5]
Disabling the custom theme and custom image does nothing.
Specifically the custom image - I don't want to see the ARES image in the menu, as it's too distracting.

I have also removed all my other mods.

![image](https://user-images.githubusercontent.com/35925402/173235971-0f2ba8c9-d1b1-446f-b6f4-f6845ea5b95a.png)

**Comment by Meowphine** [comment]
I've been having this issue as well, would be great if somebody fixed it.

**Comment by Dean2k** [comment]
Fixed as of 1.0.37
